version: '3'

networks:
  ignite-manager:
    driver: bridge
    external: true

services:

  local-bitcoin-devnet:
    container_name: local-bitcoin-devnet
    image: local-bitcoin-devnet
    build:
      context: .
      dockerfile: bitcoin-devnet.dockerfile
    environment:
      CHAIN: regtest
      RPCPORT: 18332
      # RPCPORT: 18443
      RPCUSER: rpcuser
      RPCPASS: rpcpass
    ports:
      - 18332:18332
    networks:
      - ignite-manager

  bitcoin-explorer:
    container_name: bitcoin-explorer
    image: bitcoin-explorer
    build:
      context: .
      dockerfile: bitcoin-explorer.dockerfile
    environment:
      BTCEXP_BITCOIND_HOST: local-bitcoin-devnet
      BTCEXP_BITCOIND_PORT: 18332
      BTCEXP_BITCOIND_USER: rpcuser
      BTCEXP_BITCOIND_PASS: rpcpass
      BTCEXP_HOST: 0.0.0.0
      BTCEXP_PORT: 3002
      BTCEXP_SLOW_DEVICE_MODE: false
      # BTCEXP_PRIVACY_MODE: true
      # BTCEXP_NO_RATES: true
      # BTCEXP_UI_THEME: dark
    ports:
      - 3002:3002
    networks:
      - ignite-manager
