version: '3'

services:

  ignite-manager:
    build:
      context: ..
      dockerfile: container/Dockerfile
    image: ignite-manager
    container_name: ignite-manager
    volumes:
      - ..:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_FILE
    network_mode: host
    