version: '3'

networks:
  ignite-manager:
    driver: bridge
    external: true

services:

  ignite-manager:
    build:
      context: ..
      dockerfile: container/ignite-manager.dockerfile
    image: ignite-manager
    container_name: ignite-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
      - ../go_root:/go
    environment:
      - CONFIG_FILE
      - GOFLAGS='-buildvcs=false'
    ports:
      - "1317:1317" # rest
      - "9090:9090" # prometheus
      - "26656:26656" # p2p
      - "26657:26657" # rpc
    networks:
      - ignite-manager
    