version: '3'

services:

  ignite-manager:
    build:
      context: ..
      dockerfile: container/ignite-manager.dockerfile
    image: ignite-manager
    container_name: ignite-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
      - ../go_root:/go
    environment:
      - CONFIG_FILE
    network_mode: host
    