version: '3'

networks:
  ignite-manager:
    driver: bridge
    external: true

services:

  explorer:
    container_name: explorer
    image: explorer
    build:
      context: ..
      dockerfile: container/pingpub.dockerfile
    # network_mode: host
    ports:
      - 8080:8080
    # volumes:
    #   - ../build/pingpub.json:/app/src/chains/mainnet/test.json
    networks:
      - ignite-manager
