// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mexamplechain/mexamplemodule/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateEntityName struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Field1  string `protobuf:"bytes,2,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2  int32  `protobuf:"varint,3,opt,name=field2,proto3" json:"field2,omitempty"`
}

func (m *MsgCreateEntityName) Reset()         { *m = MsgCreateEntityName{} }
func (m *MsgCreateEntityName) String() string { return proto.CompactTextString(m) }
func (*MsgCreateEntityName) ProtoMessage()    {}
func (*MsgCreateEntityName) Descriptor() ([]byte, []int) {
	return fileDescriptor_b02368263c46a91f, []int{0}
}
func (m *MsgCreateEntityName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateEntityName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateEntityName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateEntityName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateEntityName.Merge(m, src)
}
func (m *MsgCreateEntityName) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateEntityName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateEntityName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateEntityName proto.InternalMessageInfo

func (m *MsgCreateEntityName) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateEntityName) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *MsgCreateEntityName) GetField2() int32 {
	if m != nil {
		return m.Field2
	}
	return 0
}

type MsgCreateEntityNameResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateEntityNameResponse) Reset()         { *m = MsgCreateEntityNameResponse{} }
func (m *MsgCreateEntityNameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateEntityNameResponse) ProtoMessage()    {}
func (*MsgCreateEntityNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b02368263c46a91f, []int{1}
}
func (m *MsgCreateEntityNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateEntityNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateEntityNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateEntityNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateEntityNameResponse.Merge(m, src)
}
func (m *MsgCreateEntityNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateEntityNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateEntityNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateEntityNameResponse proto.InternalMessageInfo

func (m *MsgCreateEntityNameResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateEntityName struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Field1  string `protobuf:"bytes,3,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2  int32  `protobuf:"varint,4,opt,name=field2,proto3" json:"field2,omitempty"`
}

func (m *MsgUpdateEntityName) Reset()         { *m = MsgUpdateEntityName{} }
func (m *MsgUpdateEntityName) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEntityName) ProtoMessage()    {}
func (*MsgUpdateEntityName) Descriptor() ([]byte, []int) {
	return fileDescriptor_b02368263c46a91f, []int{2}
}
func (m *MsgUpdateEntityName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEntityName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEntityName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEntityName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEntityName.Merge(m, src)
}
func (m *MsgUpdateEntityName) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEntityName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEntityName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEntityName proto.InternalMessageInfo

func (m *MsgUpdateEntityName) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateEntityName) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateEntityName) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *MsgUpdateEntityName) GetField2() int32 {
	if m != nil {
		return m.Field2
	}
	return 0
}

type MsgUpdateEntityNameResponse struct {
}

func (m *MsgUpdateEntityNameResponse) Reset()         { *m = MsgUpdateEntityNameResponse{} }
func (m *MsgUpdateEntityNameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEntityNameResponse) ProtoMessage()    {}
func (*MsgUpdateEntityNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b02368263c46a91f, []int{3}
}
func (m *MsgUpdateEntityNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEntityNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEntityNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEntityNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEntityNameResponse.Merge(m, src)
}
func (m *MsgUpdateEntityNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEntityNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEntityNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEntityNameResponse proto.InternalMessageInfo

type MsgDeleteEntityName struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteEntityName) Reset()         { *m = MsgDeleteEntityName{} }
func (m *MsgDeleteEntityName) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteEntityName) ProtoMessage()    {}
func (*MsgDeleteEntityName) Descriptor() ([]byte, []int) {
	return fileDescriptor_b02368263c46a91f, []int{4}
}
func (m *MsgDeleteEntityName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteEntityName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteEntityName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteEntityName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteEntityName.Merge(m, src)
}
func (m *MsgDeleteEntityName) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteEntityName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteEntityName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteEntityName proto.InternalMessageInfo

func (m *MsgDeleteEntityName) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteEntityName) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteEntityNameResponse struct {
}

func (m *MsgDeleteEntityNameResponse) Reset()         { *m = MsgDeleteEntityNameResponse{} }
func (m *MsgDeleteEntityNameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteEntityNameResponse) ProtoMessage()    {}
func (*MsgDeleteEntityNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b02368263c46a91f, []int{5}
}
func (m *MsgDeleteEntityNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteEntityNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteEntityNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteEntityNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteEntityNameResponse.Merge(m, src)
}
func (m *MsgDeleteEntityNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteEntityNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteEntityNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteEntityNameResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateEntityName)(nil), "mexamplechain.mexamplemodule.MsgCreateEntityName")
	proto.RegisterType((*MsgCreateEntityNameResponse)(nil), "mexamplechain.mexamplemodule.MsgCreateEntityNameResponse")
	proto.RegisterType((*MsgUpdateEntityName)(nil), "mexamplechain.mexamplemodule.MsgUpdateEntityName")
	proto.RegisterType((*MsgUpdateEntityNameResponse)(nil), "mexamplechain.mexamplemodule.MsgUpdateEntityNameResponse")
	proto.RegisterType((*MsgDeleteEntityName)(nil), "mexamplechain.mexamplemodule.MsgDeleteEntityName")
	proto.RegisterType((*MsgDeleteEntityNameResponse)(nil), "mexamplechain.mexamplemodule.MsgDeleteEntityNameResponse")
}

func init() {
	proto.RegisterFile("mexamplechain/mexamplemodule/tx.proto", fileDescriptor_b02368263c46a91f)
}

var fileDescriptor_b02368263c46a91f = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcd, 0x4d, 0xad, 0x48,
	0xcc, 0x2d, 0xc8, 0x49, 0x4d, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x87, 0xf1, 0x72, 0xf3, 0x53, 0x4a,
	0x73, 0x52, 0xf5, 0x4b, 0x2a, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x64, 0x50, 0x94, 0xe9,
	0xa1, 0x2a, 0x93, 0xd2, 0xc3, 0x6b, 0x48, 0x6a, 0x5e, 0x49, 0x66, 0x49, 0x65, 0x7c, 0x5e, 0x62,
	0x6e, 0x2a, 0xc4, 0x34, 0xa5, 0x78, 0x2e, 0x61, 0xdf, 0xe2, 0x74, 0xe7, 0xa2, 0xd4, 0xc4, 0x92,
	0x54, 0x57, 0xb0, 0xac, 0x5f, 0x62, 0x6e, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x32, 0x48, 0x2c, 0xbf,
	0x48, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x15, 0x12, 0xe3, 0x62, 0x4b, 0xcb, 0x4c,
	0xcd, 0x49, 0x31, 0x94, 0x60, 0x02, 0x4b, 0x40, 0x79, 0x70, 0x71, 0x23, 0x09, 0x66, 0x05, 0x46,
	0x0d, 0x56, 0xa8, 0xb8, 0x91, 0x92, 0x2e, 0x97, 0x34, 0x16, 0x0b, 0x82, 0x52, 0x8b, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0xc0, 0x76, 0xb0, 0x04, 0x31, 0x65, 0xa6,
	0x28, 0xe5, 0x83, 0xdd, 0x13, 0x5a, 0x90, 0x42, 0xac, 0x7b, 0x20, 0x06, 0x30, 0xc1, 0x0c, 0x40,
	0x72, 0x1f, 0x33, 0x0e, 0xf7, 0xb1, 0xa0, 0xb8, 0x4f, 0x16, 0xec, 0x3e, 0x74, 0x0b, 0x61, 0xee,
	0x53, 0xb2, 0x07, 0xbb, 0xc7, 0x25, 0x35, 0x27, 0x95, 0x3c, 0xf7, 0x40, 0xcd, 0x47, 0x37, 0x00,
	0x66, 0xbe, 0x51, 0x1f, 0x33, 0x17, 0xb3, 0x6f, 0x71, 0xba, 0x50, 0x03, 0x23, 0x97, 0x00, 0x46,
	0x2c, 0x18, 0xea, 0xe1, 0x8b, 0x6b, 0x3d, 0x2c, 0xe1, 0x2a, 0x65, 0x49, 0xb2, 0x16, 0x78, 0x54,
	0x80, 0x9c, 0x80, 0x11, 0xf0, 0x84, 0x9d, 0x80, 0xae, 0x85, 0x08, 0x27, 0xe0, 0x0a, 0x6d, 0xb0,
	0x13, 0x30, 0xc2, 0x9a, 0xb0, 0x13, 0xd0, 0xb5, 0x10, 0xe1, 0x04, 0x5c, 0x11, 0xe2, 0xe4, 0x70,
	0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7,
	0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x6a, 0xb9, 0xba, 0x50, 0x63, 0x74,
	0x21, 0x99, 0xab, 0x02, 0x23, 0x8f, 0x56, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0x73, 0x96, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x95, 0x6f, 0xb6, 0xe1, 0xd0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateEntityName(ctx context.Context, in *MsgCreateEntityName, opts ...grpc.CallOption) (*MsgCreateEntityNameResponse, error)
	UpdateEntityName(ctx context.Context, in *MsgUpdateEntityName, opts ...grpc.CallOption) (*MsgUpdateEntityNameResponse, error)
	DeleteEntityName(ctx context.Context, in *MsgDeleteEntityName, opts ...grpc.CallOption) (*MsgDeleteEntityNameResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateEntityName(ctx context.Context, in *MsgCreateEntityName, opts ...grpc.CallOption) (*MsgCreateEntityNameResponse, error) {
	out := new(MsgCreateEntityNameResponse)
	err := c.cc.Invoke(ctx, "/mexamplechain.mexamplemodule.Msg/CreateEntityName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateEntityName(ctx context.Context, in *MsgUpdateEntityName, opts ...grpc.CallOption) (*MsgUpdateEntityNameResponse, error) {
	out := new(MsgUpdateEntityNameResponse)
	err := c.cc.Invoke(ctx, "/mexamplechain.mexamplemodule.Msg/UpdateEntityName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteEntityName(ctx context.Context, in *MsgDeleteEntityName, opts ...grpc.CallOption) (*MsgDeleteEntityNameResponse, error) {
	out := new(MsgDeleteEntityNameResponse)
	err := c.cc.Invoke(ctx, "/mexamplechain.mexamplemodule.Msg/DeleteEntityName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateEntityName(context.Context, *MsgCreateEntityName) (*MsgCreateEntityNameResponse, error)
	UpdateEntityName(context.Context, *MsgUpdateEntityName) (*MsgUpdateEntityNameResponse, error)
	DeleteEntityName(context.Context, *MsgDeleteEntityName) (*MsgDeleteEntityNameResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateEntityName(ctx context.Context, req *MsgCreateEntityName) (*MsgCreateEntityNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntityName not implemented")
}
func (*UnimplementedMsgServer) UpdateEntityName(ctx context.Context, req *MsgUpdateEntityName) (*MsgUpdateEntityNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEntityName not implemented")
}
func (*UnimplementedMsgServer) DeleteEntityName(ctx context.Context, req *MsgDeleteEntityName) (*MsgDeleteEntityNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntityName not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateEntityName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateEntityName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateEntityName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mexamplechain.mexamplemodule.Msg/CreateEntityName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateEntityName(ctx, req.(*MsgCreateEntityName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateEntityName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateEntityName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateEntityName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mexamplechain.mexamplemodule.Msg/UpdateEntityName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateEntityName(ctx, req.(*MsgUpdateEntityName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteEntityName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteEntityName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteEntityName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mexamplechain.mexamplemodule.Msg/DeleteEntityName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteEntityName(ctx, req.(*MsgDeleteEntityName))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mexamplechain.mexamplemodule.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntityName",
			Handler:    _Msg_CreateEntityName_Handler,
		},
		{
			MethodName: "UpdateEntityName",
			Handler:    _Msg_UpdateEntityName_Handler,
		},
		{
			MethodName: "DeleteEntityName",
			Handler:    _Msg_DeleteEntityName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mexamplechain/mexamplemodule/tx.proto",
}

func (m *MsgCreateEntityName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateEntityName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateEntityName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Field2 != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Field2))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Field1) > 0 {
		i -= len(m.Field1)
		copy(dAtA[i:], m.Field1)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Field1)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateEntityNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateEntityNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateEntityNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateEntityName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEntityName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEntityName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Field2 != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Field2))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Field1) > 0 {
		i -= len(m.Field1)
		copy(dAtA[i:], m.Field1)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Field1)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateEntityNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEntityNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEntityNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteEntityName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteEntityName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteEntityName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteEntityNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteEntityNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteEntityNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateEntityName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Field1)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Field2 != 0 {
		n += 1 + sovTx(uint64(m.Field2))
	}
	return n
}

func (m *MsgCreateEntityNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateEntityName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Field1)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Field2 != 0 {
		n += 1 + sovTx(uint64(m.Field2))
	}
	return n
}

func (m *MsgUpdateEntityNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteEntityName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteEntityNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateEntityName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateEntityName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateEntityName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Field1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field2", wireType)
			}
			m.Field2 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Field2 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateEntityNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateEntityNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateEntityNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateEntityName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEntityName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEntityName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Field1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field2", wireType)
			}
			m.Field2 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Field2 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateEntityNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEntityNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEntityNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteEntityName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteEntityName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteEntityName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteEntityNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteEntityNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteEntityNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
