ignite:
  config: !include config.yml
  framework:
    type: rollkit
    versions:
      cosmos-sdk: v0.46.7-rollkit-v0.7.2-no-fraud-proofs
      tendermint: v0.34.22-0.20221202214355-3605c597500d

chain:
  name: examplechain
  prefix: ex

module:
  name: examplemodule

models:
  - name: entity_name
    type: list
    attributes:
      - field1:string
      - field2:int
    events: true
    custom_files:
      - custom_entity.go

  - name: resource_name
    type: list
    attributes:
      - owner:string
      - name:string
      - category:string
      - value:int
