// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateEntityName } from "./types/mexamplechain/mexamplemodule/tx";
import { MsgDeleteEntityName } from "./types/mexamplechain/mexamplemodule/tx";
import { MsgUpdateEntityName } from "./types/mexamplechain/mexamplemodule/tx";

import { EntityName as typeEntityName} from "./types"
import { Params as typeParams} from "./types"

export { MsgCreateEntityName, MsgDeleteEntityName, MsgUpdateEntityName };

type sendMsgCreateEntityNameParams = {
  value: MsgCreateEntityName,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteEntityNameParams = {
  value: MsgDeleteEntityName,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateEntityNameParams = {
  value: MsgUpdateEntityName,
  fee?: StdFee,
  memo?: string
};


type msgCreateEntityNameParams = {
  value: MsgCreateEntityName,
};

type msgDeleteEntityNameParams = {
  value: MsgDeleteEntityName,
};

type msgUpdateEntityNameParams = {
  value: MsgUpdateEntityName,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateEntityName({ value, fee, memo }: sendMsgCreateEntityNameParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateEntityName: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateEntityName({ value: MsgCreateEntityName.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateEntityName: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteEntityName({ value, fee, memo }: sendMsgDeleteEntityNameParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteEntityName: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteEntityName({ value: MsgDeleteEntityName.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteEntityName: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateEntityName({ value, fee, memo }: sendMsgUpdateEntityNameParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateEntityName: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateEntityName({ value: MsgUpdateEntityName.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateEntityName: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateEntityName({ value }: msgCreateEntityNameParams): EncodeObject {
			try {
				return { typeUrl: "/mexamplechain.mexamplemodule.MsgCreateEntityName", value: MsgCreateEntityName.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateEntityName: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteEntityName({ value }: msgDeleteEntityNameParams): EncodeObject {
			try {
				return { typeUrl: "/mexamplechain.mexamplemodule.MsgDeleteEntityName", value: MsgDeleteEntityName.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteEntityName: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateEntityName({ value }: msgUpdateEntityNameParams): EncodeObject {
			try {
				return { typeUrl: "/mexamplechain.mexamplemodule.MsgUpdateEntityName", value: MsgUpdateEntityName.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateEntityName: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						EntityName: getStructure(typeEntityName.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			MexamplechainMexamplemodule: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;