accounts:
- coins:
  - 20000token
  - 200000000stake
  mnemonic: winter blur imitate this open palace reward steel local noodle believe
    into evil other rebuild ready fuel someone body capital review mixture absurd
    seminar
  name: alice
- coins:
  - 10000token
  - 100000000stake
  mnemonic: mammal artist elbow chaos oak gym practice oblige local decrease fetch
    boat inner same artist veteran catalog cannon fat forest tail boat must observe
  name: bob
client:
  openapi:
    path: docs/static/openapi.yml
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
faucet:
  coins:
  - 5token
  - 100000stake
  name: alice
init:
  config:
    api:
      address: tcp://0.0.0.0:1317
      enable: true
      max-open-connections: 1000
      swagger: false
validators:
- bonded: 100000000stake
  name: alice
version: 1
